INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (6, 23, 0, '2226 Massachusetts Avenue', 'Cambridge', 'Massachusetts', 2140);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (14, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (7, 33, 0, '353 Greenwich Street', 'New York', 'New York', 10013);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (58, 33, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (19, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (10, 22, 0, '2095 3rd Avenue', 'New York Test', 'New York', 10029);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (25, 2, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (60, 22, 0, '2225 Massachusetts Avenue', 'Cambridge', 'Massachusetts', 2140);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (59, 22, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (57, 111, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (1, 2, 0, '3333 14th Street Northwest', 'Washington', 'District of Columbia', 20010);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (13, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (8, 3333, 0, '333 Ballarat Road', 'Braybrook', 'Victoria', 3019);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (11, 22, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (21, 23, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (17, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (9, 22, 0, '2095 3rd Avenue', 'New York Test', 'New York', 10029);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (24, 22, 0, '2222 U.S. 1', 'Vero Beach', 'Florida', 32960);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (20, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (23, 29, 0, '2212 Avenida Corrientes', 'CDN', 'Buenos Aires', 2992);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (3, 44, 0, '2095 3rd Avenue', 'New York', 'New York', 10029);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (2, 33, 0, '353 Greenwich Street', 'New York', 'New York', 10013);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (4, 33, 0, '353 Greenwich Street', 'New York', 'New York', 10013);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (5, 23, 0, '2226 Massachusetts Avenue', 'Cambridge', 'Massachusetts', 2140);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (56, 11, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (22, 23, 0, '92 Station Street', 'Carlton', 'VIC', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (15, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (16, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (18, 22, 0, '92 Station Street', 'Carlton', 'Buenos Aires', 3053);
INSERT INTO public.address (id, unit_no, street_no, street_name, city, state, post_code) VALUES (12, 22, 0, '92 Station Street', 'Carlton', 'VIC', 3053);